---
title: "Corona_Case_Prediction"
author: "Steven Smith, PhD"
date: "3/18/2020"
output: 
  html_document: 
    toc: yes
---

```{r}
library(ggplot2)
library(tidyverse)
library(plyr)
library(plot.utils)

Corona_Cases<-read.csv("/Users/stevensmith/Dropbox (Personal)/total-cases-covid-19.csv",header = T)

Corona_Cases<-Corona_Cases %>% rename(replace = c("Total.confirmed.cases.of.COVID.19..cases."="Total_confirmed_cases","Year"="Days_Since_x"))

Corona_Cases$Total_confirmed_cases.log<-log(Corona_Cases$Total_confirmed_cases,10)


head(Corona_Cases)

plot_data<-Corona_Cases[Corona_Cases$Code=="USA" & Corona_Cases$Days_Since_x>0,]
(model_fit<-lm(formula = Total_confirmed_cases.log~Days_Since_x,data =plot_data[plot_data$Days_Since_x>40,] ))
slope<-model_fit$coefficients[2]
intercept<-model_fit$coefficients[1]
cor(x = plot_data[plot_data$Days_Since_x>40,"Days_Since_x"],y = plot_data[plot_data$Days_Since_x>40,"Total_confirmed_cases.log"])

ggplot(plot_data,aes(x=Days_Since_x,y=Total_confirmed_cases))+
  geom_point()

ggplot(plot_data,aes(x=Days_Since_x,y=Total_confirmed_cases.log))+
  geom_abline(slope = slope,intercept = intercept,lty=2)+
  geom_point()


```
# What is the prediction of COVID-19 based on model thus far?
WHy did it take to day 40 to start a log linear trend?
How long will it be till x number of cases?
When will the plateu happen?
Are any effects noticed with social distancing? Delays
```{r prediction, eval=FALSE}
#Corona_Cases$Total.confirmed.cases.of.COVID.19..cases.
#Corona_Prediction<-read.table("/Users/ssmith/Dropbox (Personal)/Corona_Prediction",header = T,sep = "\t",stringsAsFactors = F)
Corona_Prediction$type<-"Predicted"
Corona_Cases$type<-"Actual"
Corona<-rbind(Corona_Prediction,Corona_Cases)
Corona$Active_US_cases.log<-log(Corona$Active_US_cases,2)
estimate_model<-lm(Corona,formula = Active_US_cases.log~Days_since_Mar17)
slope<-estimate_model$coefficients[2]
intercept<-estimate_model$coefficients[1]
fit<-cor(log(Corona_Cases$Active_US_cases,2),Corona_Cases$Days_since_Mar17)
key_milestones<-log(c(1E5,5E5,1E6),2)
key_milestones.days<-(key_milestones - intercept)/slope
Corona<-rbind(Corona,data.frame(Days_since_Mar17=key_milestones.days,Active_US_cases=2^key_milestones,Active_US_cases.log=key_milestones,type="Predicted"))
(Corona.plot<-ggplot(Corona,aes(x=Days_since_Mar17,y=Active_US_cases.log,col=type))+
    geom_abline(slope = slope,intercept = intercept,lty=2)+
  geom_vline(xintercept = c(key_milestones.days),lty=2)+
  geom_point(size=3)+
  theme_bw()+
  ylab("log2 Total U.S. Cases")+
  xlab("Days since March 17, 2020")+
  default_theme+
  theme(legend.position = "bottom",axis.ticks.x = element_line(Corona$Days_since_Mar17))+
  scale_color_manual(values = c("Actual"="#377eb8","Predicted"="#e41a1c")))
  

write_plot(Corona.plot,wd = "/Users/ssmith/Dropbox (Personal)/")
```

